"""
joint_schema.py
---------------
Single source of truth for joint UI configuration.

Each entry covers one joint group (Head / Waist / Left Arm / Right Arm /
Left Leg / Right Leg / Left Hand / Right Hand).

Per-joint fields
----------------
name            : joint name (must match URDF & ROS topics)
display         : label shown in the slider UI
motor_id        : body-motor integer ID; None for hand joints
is_hand         : True  → hand slider (1000=open, -1000=closed, display=0..1)
                  False → body slider (-1000=min, 1000=max, display in rad)
default_slider  : initial slider integer value (-1000 … 1000)
min / max       : URDF lower/upper limit in radians (reference – actual
                  runtime limits come from the URDF parsed by _load_urdf)
step            : step size (not yet wired in UI, reserved for future use)
coupling        : follower joints moved together with this joint (mimic)
hand_motor_id   : index 1-6 used by the hand controller; None for body joints
hand_limit      : upper-limit used for the rad ↔ percentage conversion in
                  publish_hands / execute_commands; None for body joints
"""

JOINT_SCHEMA = [
    # ------------------------------------------------------------------ Head
    {
        "group": "Head",
        "ui_visible": True,
        "joints": [
            {
                "name": "head_yaw_joint",
                "display": "head_yaw_joint",
                "motor_id": 3,
                "is_hand": False,
                "default_slider": 0,
                "min": -1.5708,
                "max":  1.5708,
                "step": None,
                "coupling": [],
                "hand_motor_id": None,
                "hand_limit": None,
            },
            {
                "name": "head_pitch_joint",
                "display": "head_pitch_joint",
                "motor_id": 2,
                "is_hand": False,
                "default_slider": 0,
                "min": -0.4363,
                "max":  0.4363,
                "step": None,
                "coupling": [],
                "hand_motor_id": None,
                "hand_limit": None,
            },
            {
                "name": "head_roll_joint",
                "display": "head_roll_joint",
                "motor_id": 1,
                "is_hand": False,
                "default_slider": 0,
                "min": -0.4538,
                "max":  0.4538,
                "step": None,
                "coupling": [],
                "hand_motor_id": None,
                "hand_limit": None,
            },
        ],
    },
    # ----------------------------------------------------------------- Waist
    {
        "group": "Waist",
        "ui_visible": True,
        "joints": [
            {
                "name": "body_yaw_joint",
                "display": "body_yaw_joint",
                "motor_id": 31,
                "is_hand": False,
                "default_slider": 0,
                "min": -2.9671,
                "max":  3.1416,
                "step": None,
                "coupling": [],
                "hand_motor_id": None,
                "hand_limit": None,
            },
        ],
    },
    # --------------------------------------------------------------- Left Arm
    {
        "group": "Left Arm",
        "ui_visible": True,
        "joints": [
            {
                "name": "shoulder_pitch_l_joint",
                "display": "shoulder_pitch_l_joint",
                "motor_id": 11,
                "is_hand": False,
                "default_slider": 0,
                "min": -2.9671,
                "max":  2.9671,
                "step": None,
                "coupling": [],
                "hand_motor_id": None,
                "hand_limit": None,
            },
            {
                "name": "shoulder_roll_l_joint",
                "display": "shoulder_roll_l_joint",
                "motor_id": 12,
                "is_hand": False,
                "default_slider": 0,
                "min": -0.2618,
                "max":  2.6180,
                "step": None,
                "coupling": [],
                "hand_motor_id": None,
                "hand_limit": None,
            },
            {
                "name": "shoulder_yaw_l_joint",
                "display": "shoulder_yaw_l_joint",
                "motor_id": 13,
                "is_hand": False,
                "default_slider": 0,
                "min": -2.9671,
                "max":  2.9671,
                "step": None,
                "coupling": [],
                "hand_motor_id": None,
                "hand_limit": None,
            },
            {
                "name": "elbow_pitch_l_joint",
                "display": "elbow_pitch_l_joint",
                "motor_id": 14,
                "is_hand": False,
                "default_slider": 0,
                "min": -2.6180,
                "max":  0.2618,
                "step": None,
                "coupling": [],
                "hand_motor_id": None,
                "hand_limit": None,
            },
            {
                "name": "elbow_yaw_l_joint",
                "display": "elbow_yaw_l_joint",
                "motor_id": 15,
                "is_hand": False,
                "default_slider": 0,
                "min": -2.9671,
                "max":  2.9671,
                "step": None,
                "coupling": [],
                "hand_motor_id": None,
                "hand_limit": None,
            },
            {
                "name": "wrist_pitch_l_joint",
                "display": "wrist_pitch_l_joint",
                "motor_id": 16,
                "is_hand": False,
                "default_slider": 0,
                "min": -0.7854,
                "max":  1.0472,
                "step": None,
                "coupling": [],
                "hand_motor_id": None,
                "hand_limit": None,
            },
            {
                "name": "wrist_roll_l_joint",
                "display": "wrist_roll_l_joint",
                "motor_id": 17,
                "is_hand": False,
                "default_slider": 0,
                "min": -1.6581,
                "max":  1.3090,
                "step": None,
                "coupling": [],
                "hand_motor_id": None,
                "hand_limit": None,
            },
        ],
    },
    # -------------------------------------------------------------- Right Arm
    {
        "group": "Right Arm",
        "ui_visible": True,
        "joints": [
            {
                "name": "shoulder_pitch_r_joint",
                "display": "shoulder_pitch_r_joint",
                "motor_id": 21,
                "is_hand": False,
                "default_slider": 0,
                "min": -2.9671,
                "max":  2.9671,
                "step": None,
                "coupling": [],
                "hand_motor_id": None,
                "hand_limit": None,
            },
            {
                "name": "shoulder_roll_r_joint",
                "display": "shoulder_roll_r_joint",
                "motor_id": 22,
                "is_hand": False,
                "default_slider": 0,
                "min": -2.6180,
                "max":  0.2618,
                "step": None,
                "coupling": [],
                "hand_motor_id": None,
                "hand_limit": None,
            },
            {
                "name": "shoulder_yaw_r_joint",
                "display": "shoulder_yaw_r_joint",
                "motor_id": 23,
                "is_hand": False,
                "default_slider": 0,
                "min": -2.9671,
                "max":  2.9671,
                "step": None,
                "coupling": [],
                "hand_motor_id": None,
                "hand_limit": None,
            },
            {
                "name": "elbow_pitch_r_joint",
                "display": "elbow_pitch_r_joint",
                "motor_id": 24,
                "is_hand": False,
                "default_slider": 0,
                "min": -2.6180,
                "max":  0.2618,
                "step": None,
                "coupling": [],
                "hand_motor_id": None,
                "hand_limit": None,
            },
            {
                "name": "elbow_yaw_r_joint",
                "display": "elbow_yaw_r_joint",
                "motor_id": 25,
                "is_hand": False,
                "default_slider": 0,
                "min": -2.9671,
                "max":  2.9671,
                "step": None,
                "coupling": [],
                "hand_motor_id": None,
                "hand_limit": None,
            },
            {
                "name": "wrist_pitch_r_joint",
                "display": "wrist_pitch_r_joint",
                "motor_id": 26,
                "is_hand": False,
                "default_slider": 0,
                "min": -0.7854,
                "max":  1.0472,
                "step": None,
                "coupling": [],
                "hand_motor_id": None,
                "hand_limit": None,
            },
            {
                "name": "wrist_roll_r_joint",
                "display": "wrist_roll_r_joint",
                "motor_id": 27,
                "is_hand": False,
                "default_slider": 0,
                "min": -1.3090,
                "max":  1.6581,
                "step": None,
                "coupling": [],
                "hand_motor_id": None,
                "hand_limit": None,
            },
        ],
    },
    # --------------------------------------------------------------- Left Leg
    {
        "group": "Left Leg",
        "ui_visible": False,  # hidden from slider UI; logic retained
        "joints": [
            {
                "name": "hip_roll_l_joint",
                "display": "hip_roll_l_joint",
                "motor_id": 51,
                "is_hand": False,
                "default_slider": 0,
                "min": -0.7854,
                "max":  0.7854,
                "step": None,
                "coupling": [],
                "hand_motor_id": None,
                "hand_limit": None,
            },
            {
                "name": "hip_pitch_l_joint",
                "display": "hip_pitch_l_joint",
                "motor_id": 52,
                "is_hand": False,
                "default_slider": 0,
                "min": -2.7925,
                "max":  2.0944,
                "step": None,
                "coupling": [],
                "hand_motor_id": None,
                "hand_limit": None,
            },
            {
                "name": "hip_yaw_l_joint",
                "display": "hip_yaw_l_joint",
                "motor_id": 53,
                "is_hand": False,
                "default_slider": 0,
                "min": -1.0472,
                "max":  1.0472,
                "step": None,
                "coupling": [],
                "hand_motor_id": None,
                "hand_limit": None,
            },
            {
                "name": "knee_pitch_l_joint",
                "display": "knee_pitch_l_joint",
                "motor_id": 54,
                "is_hand": False,
                "default_slider": 0,
                "min":  0.0,
                "max":  2.3911,
                "step": None,
                "coupling": [],
                "hand_motor_id": None,
                "hand_limit": None,
            },
            {
                "name": "ankle_pitch_l_joint",
                "display": "ankle_pitch_l_joint",
                "motor_id": 55,
                "is_hand": False,
                "default_slider": 0,
                "min": -1.2217,
                "max":  0.5236,
                "step": None,
                "coupling": [],
                "hand_motor_id": None,
                "hand_limit": None,
            },
            {
                "name": "ankle_roll_l_joint",
                "display": "ankle_roll_l_joint",
                "motor_id": 56,
                "is_hand": False,
                "default_slider": 0,
                "min": -0.5236,
                "max":  0.5236,
                "step": None,
                "coupling": [],
                "hand_motor_id": None,
                "hand_limit": None,
            },
        ],
    },
    # -------------------------------------------------------------- Right Leg
    {
        "group": "Right Leg",
        "ui_visible": False,  # hidden from slider UI; logic retained
        "joints": [
            {
                "name": "hip_roll_r_joint",
                "display": "hip_roll_r_joint",
                "motor_id": 61,
                "is_hand": False,
                "default_slider": 0,
                "min": -0.7854,
                "max":  0.7854,
                "step": None,
                "coupling": [],
                "hand_motor_id": None,
                "hand_limit": None,
            },
            {
                "name": "hip_pitch_r_joint",
                "display": "hip_pitch_r_joint",
                "motor_id": 62,
                "is_hand": False,
                "default_slider": 0,
                "min": -2.7925,
                "max":  2.0944,
                "step": None,
                "coupling": [],
                "hand_motor_id": None,
                "hand_limit": None,
            },
            {
                "name": "hip_yaw_r_joint",
                "display": "hip_yaw_r_joint",
                "motor_id": 63,
                "is_hand": False,
                "default_slider": 0,
                "min": -1.0472,
                "max":  1.0472,
                "step": None,
                "coupling": [],
                "hand_motor_id": None,
                "hand_limit": None,
            },
            {
                "name": "knee_pitch_r_joint",
                "display": "knee_pitch_r_joint",
                "motor_id": 64,
                "is_hand": False,
                "default_slider": 0,
                "min":  0.0,
                "max":  2.3911,
                "step": None,
                "coupling": [],
                "hand_motor_id": None,
                "hand_limit": None,
            },
            {
                "name": "ankle_pitch_r_joint",
                "display": "ankle_pitch_r_joint",
                "motor_id": 65,
                "is_hand": False,
                "default_slider": 0,
                "min": -1.2217,
                "max":  0.5236,
                "step": None,
                "coupling": [],
                "hand_motor_id": None,
                "hand_limit": None,
            },
            {
                "name": "ankle_roll_r_joint",
                "display": "ankle_roll_r_joint",
                "motor_id": 66,
                "is_hand": False,
                "default_slider": 0,
                "min": -0.5236,
                "max":  0.5236,
                "step": None,
                "coupling": [],
                "hand_motor_id": None,
                "hand_limit": None,
            },
        ],
    },
    # -------------------------------------------------------------- Left Hand
    {
        "group": "Left Hand",
        "ui_visible": True,
        "joints": [
            {
                "name": "left_little_1_joint",
                "display": "left_little",
                "motor_id": None,
                "is_hand": True,
                "default_slider": 1000,
                "min": 0.0,
                "max": 1.333,
                "step": None,
                "coupling": ["left_little_2_joint"],
                "hand_motor_id": 1,
                "hand_limit": 1.333,
            },
            {
                "name": "left_ring_1_joint",
                "display": "left_ring",
                "motor_id": None,
                "is_hand": True,
                "default_slider": 1000,
                "min": 0.0,
                "max": 1.333,
                "step": None,
                "coupling": ["left_ring_2_joint"],
                "hand_motor_id": 2,
                "hand_limit": 1.333,
            },
            {
                "name": "left_middle_1_joint",
                "display": "left_middle",
                "motor_id": None,
                "is_hand": True,
                "default_slider": 1000,
                "min": 0.0,
                "max": 1.333,
                "step": None,
                "coupling": ["left_middle_2_joint"],
                "hand_motor_id": 3,
                "hand_limit": 1.333,
            },
            {
                "name": "left_index_1_joint",
                "display": "left_index",
                "motor_id": None,
                "is_hand": True,
                "default_slider": 1000,
                "min": 0.0,
                "max": 1.333,
                "step": None,
                "coupling": ["left_index_2_joint"],
                "hand_motor_id": 4,
                "hand_limit": 1.333,
            },
            {
                "name": "left_thumb_1_joint",
                "display": "left_thumb_rotation",
                "motor_id": None,
                "is_hand": True,
                "default_slider": 1000,
                "min": 0.0,
                "max": 1.246165,
                "step": None,
                "coupling": [],
                "hand_motor_id": 6,
                "hand_limit": 1.246165,
            },
            {
                "name": "left_thumb_2_joint",
                "display": "left_thumb",
                "motor_id": None,
                "is_hand": True,
                "default_slider": 1000,
                "min": 0.0,
                "max": 0.48,
                "step": None,
                "coupling": ["left_thumb_3_joint", "left_thumb_4_joint"],
                "hand_motor_id": 5,
                "hand_limit": 0.48,
            },
        ],
    },
    # ------------------------------------------------------------- Right Hand
    {
        "group": "Right Hand",
        "ui_visible": True,
        "joints": [
            {
                "name": "right_little_1_joint",
                "display": "right_little",
                "motor_id": None,
                "is_hand": True,
                "default_slider": 1000,
                "min": 0.0,
                "max": 1.333,
                "step": None,
                "coupling": ["right_little_2_joint"],
                "hand_motor_id": 1,
                "hand_limit": 1.333,
            },
            {
                "name": "right_ring_1_joint",
                "display": "right_ring",
                "motor_id": None,
                "is_hand": True,
                "default_slider": 1000,
                "min": 0.0,
                "max": 1.333,
                "step": None,
                "coupling": ["right_ring_2_joint"],
                "hand_motor_id": 2,
                "hand_limit": 1.333,
            },
            {
                "name": "right_middle_1_joint",
                "display": "right_middle",
                "motor_id": None,
                "is_hand": True,
                "default_slider": 1000,
                "min": 0.0,
                "max": 1.333,
                "step": None,
                "coupling": ["right_middle_2_joint"],
                "hand_motor_id": 3,
                "hand_limit": 1.333,
            },
            {
                "name": "right_index_1_joint",
                "display": "right_index",
                "motor_id": None,
                "is_hand": True,
                "default_slider": 1000,
                "min": 0.0,
                "max": 1.333,
                "step": None,
                "coupling": ["right_index_2_joint"],
                "hand_motor_id": 4,
                "hand_limit": 1.333,
            },
            {
                "name": "right_thumb_1_joint",
                "display": "right_thumb_rotation",
                "motor_id": None,
                "is_hand": True,
                "default_slider": 1000,
                "min": 0.0,
                "max": 1.246165,
                "step": None,
                "coupling": [],
                "hand_motor_id": 6,
                "hand_limit": 1.246165,
            },
            {
                "name": "right_thumb_2_joint",
                "display": "right_thumb",
                "motor_id": None,
                "is_hand": True,
                "default_slider": 1000,
                "min": 0.0,
                "max": 0.48,
                "step": None,
                "coupling": ["right_thumb_3_joint", "right_thumb_4_joint"],
                "hand_motor_id": 5,
                "hand_limit": 0.48,
            },
        ],
    },
]

# ---------------------------------------------------------------------------
# Convenience helpers (used by interactive_gui.py)
# ---------------------------------------------------------------------------

# Fast name → entry lookup
JOINT_MAP: dict = {
    j["name"]: j
    for g in JOINT_SCHEMA
    for j in g["joints"]
}

# GROUPS dict (group_name → [joint_name, ...]) – same shape as the old
# hard-coded GROUPS in interactive_gui.py, now derived from schema.
GROUPS: dict = {
    g["group"]: [j["name"] for j in g["joints"]]
    for g in JOINT_SCHEMA
}

# HAND_JOINTS dict (side → {hand_motor_id: (joint_name, hand_limit)}) –
# same shape as the old hard-coded HAND_JOINTS dict.
HAND_JOINTS: dict = {
    "left": {
        j["hand_motor_id"]: (j["name"], j["hand_limit"])
        for j in next(g["joints"] for g in JOINT_SCHEMA if g["group"] == "Left Hand")
    },
    "right": {
        j["hand_motor_id"]: (j["name"], j["hand_limit"])
        for j in next(g["joints"] for g in JOINT_SCHEMA if g["group"] == "Right Hand")
    },
}
